<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HR Management</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/app.css"></head><body>
<header class="workspace-header">
<a class="brand" href="${pageContext.request.contextPath}/dashboard"><span class="brand-symbol">p.</span><span>PeopleDesk<small>YOUR PEOPLE WORKSPACE</small></span></a>
<p class="nav-label">WORKSPACE</p>
<nav aria-label="Main navigation">
<a class="" href="${pageContext.request.contextPath}/dashboard"><span class="nav-icon">◈</span>Overview</a>
<c:if test="${me.role == 'ADMIN'}"><a class="" href="${pageContext.request.contextPath}/employees"><span class="nav-icon">♧</span>Employees</a></c:if>
<a class="active" href="${pageContext.request.contextPath}/absences"><span class="nav-icon">◷</span>Absences</a>
<a class="" href="${pageContext.request.contextPath}/messages"><span class="nav-icon">✉</span>Messages</a>
<a class="" href="${pageContext.request.contextPath}/schedule"><span class="nav-icon">▦</span>Planning</a>
<a class="" href="${pageContext.request.contextPath}/profile"><span class="nav-icon">◎</span>Profile</a>
</nav>
<section class="sidebar-tip"><span class="tip-dot"></span><strong>A little more organized.</strong><p>One space for your team,<br>your time and your next step.</p></section>
<div class="sidebar-account"><span class="avatar">${me.role == 'ADMIN' ? 'AD' : 'EM'}</span><div><strong><c:out value="${me.name}"/></strong><small>${me.role == 'ADMIN' ? 'Administrator' : 'Employee'}</small></div></div>
<form method="post" action="${pageContext.request.contextPath}/logout"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><button class="quiet">↗ Sign out</button></form>
</header>
<div class="topbar"><span>Workspace <span class="breadcrumb-divider">/</span> <strong>People management</strong></span><span class="workspace-pill"><span class="status-dot"></span>${me.role == 'ADMIN' ? 'Admin workspace' : 'Employee workspace'}</span></div><main><c:if test="${not empty notice}"><p class="notice" role="status"><c:out value="${notice}"/></p></c:if>
<p class="eyebrow">TIME AWAY</p><h1>Absences</h1><c:if test="${me.role == 'ADMIN'}"><section class="card"><h2>Record an absence</h2><form class="grid" method="post" action="${pageContext.request.contextPath}/absences"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><label>Employee<select name="employee"><c:forEach var="e" items="${employees}"><option value="${e.id}"><c:out value="${e.name}"/></option></c:forEach></select></label><label>Start date<input type="date" name="date" required></label><label>Duration in days<input type="number" name="days" min="1" max="365" required></label><label>Reason<input name="reason" maxlength="500" required></label><button>Save absence</button></form></section></c:if><section class="card table"><table><thead><tr><th>Employee</th><th>Start</th><th>Days</th><th>Reason</th><c:if test="${me.role == 'ADMIN'}"><th>Action</th></c:if></tr></thead><tbody><c:forEach var="a" items="${absences}"><tr><td><c:out value="${a.name}"/></td><td><c:out value="${a.start_date}"/></td><td>${a.days}</td><td><c:out value="${a.reason}"/></td><c:if test="${me.role == 'ADMIN'}"><td><form method="post" action="${pageContext.request.contextPath}/absences"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="${a.id}"><button class="danger">Delete</button></form></td></c:if></tr></c:forEach></tbody></table><c:if test="${empty absences}"><p>No absences recorded.</p></c:if></section></main><footer>PeopleDesk · A better day at work</footer></body></html>