<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HR Management</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/app.css"></head><body>
<header class="workspace-header">
<a class="brand" href="${pageContext.request.contextPath}/dashboard"><span class="brand-symbol">p.</span><span>PeopleDesk<small>YOUR PEOPLE WORKSPACE</small></span></a>
<p class="nav-label">WORKSPACE</p>
<nav aria-label="Main navigation">
<a class="active" href="${pageContext.request.contextPath}/dashboard"><span class="nav-icon">◈</span>Overview</a>
<c:if test="${me.role == 'ADMIN'}"><a class="" href="${pageContext.request.contextPath}/employees"><span class="nav-icon">♧</span>Employees</a></c:if>
<a class="" href="${pageContext.request.contextPath}/absences"><span class="nav-icon">◷</span>Absences</a>
<a class="" href="${pageContext.request.contextPath}/messages"><span class="nav-icon">✉</span>Messages</a>
<a class="" href="${pageContext.request.contextPath}/schedule"><span class="nav-icon">▦</span>Planning</a>
<a class="" href="${pageContext.request.contextPath}/profile"><span class="nav-icon">◎</span>Profile</a>
</nav>
<section class="sidebar-tip"><span class="tip-dot"></span><strong>A little more organized.</strong><p>One space for your team,<br>your time and your next step.</p></section>
<div class="sidebar-account"><span class="avatar">${me.role == 'ADMIN' ? 'AD' : 'EM'}</span><div><strong><c:out value="${me.name}"/></strong><small>${me.role == 'ADMIN' ? 'Administrator' : 'Employee'}</small></div></div>
<form method="post" action="${pageContext.request.contextPath}/logout"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><button class="quiet">↗ Sign out</button></form>
</header>
<div class="topbar"><span>Workspace <span class="breadcrumb-divider">/</span> <strong>People management</strong></span><span class="workspace-pill"><span class="status-dot"></span>${me.role == 'ADMIN' ? 'Admin workspace' : 'Employee workspace'}</span></div><main><c:if test="${not empty notice}"><p class="notice" role="status"><c:out value="${notice}"/></p></c:if>
<div class="page-heading"><div><p class="eyebrow">YOUR WORKDAY, SIMPLIFIED</p><h1>Welcome, <c:out value="${me.name}"/>.</h1><p>Everything you need to keep your people moving forward.</p></div><a class="button secondary" href="${pageContext.request.contextPath}/profile">Your profile ↗</a></div>
<section class="hero"><div class="hero-copy"><span class="hero-tag">PEOPLE FIRST. ALWAYS.</span><h2>A connected team.<br>A clearer week.</h2><p>Bring your conversations, time away and weekly assignments together in one calm workspace.</p><a class="button" href="${pageContext.request.contextPath}/schedule">Explore weekly planning <span>↗</span></a></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-card art-card-one"><span class="art-avatar">◈</span><span>People<br><b>Connected</b></span><i>✓</i></div><div class="art-card art-card-two"><span class="art-avatar mint">▦</span><span>Your week<br><b>In focus</b></span><i>✓</i></div><div class="art-caption">Small steps. Better teamwork.</div></div></section>
<div class="stats"><section class="card stat"><div class="stat-top"><h2>Team members</h2><span class="stat-icon lavender">♧</span></div><strong>${employeeCount}</strong><p>People in your workspace</p></section><section class="card stat"><div class="stat-top"><h2>Your absences</h2><span class="stat-icon peach">◷</span></div><strong>${absenceCount}</strong><p>Your recorded time away</p></section><section class="card stat"><div class="stat-top"><h2>Received messages</h2><span class="stat-icon mint">✉</span></div><strong>${messageCount}</strong><p>Conversations in your inbox</p></section></div>
<div class="section-heading"><div><p class="eyebrow">MAKE YOUR NEXT MOVE</p><h2>Workspace essentials</h2></div><span>Built around your day</span></div>
<div class="quick-grid"><a class="quick-card" href="${pageContext.request.contextPath}/messages"><span class="quick-icon lavender">✉</span><h3>Keep the conversation going</h3><p>Read incoming messages or reach out to someone on your team.</p><span class="quick-link">Open messages ↗</span></a><a class="quick-card" href="${pageContext.request.contextPath}/absences"><span class="quick-icon peach">◷</span><h3>A clear view of time away</h3><p>${me.role == 'ADMIN' ? 'Record and review absences across your team.' : 'Find your recorded absences in one place.'}</p><span class="quick-link">View absences ↗</span></a><c:choose><c:when test="${me.role == 'ADMIN'}"><a class="quick-card" href="${pageContext.request.contextPath}/employees"><span class="quick-icon mint">♧</span><h3>Your people, in one place</h3><p>Manage employee details, positions and workspace access.</p><span class="quick-link">Manage employees ↗</span></a></c:when><c:otherwise><a class="quick-card" href="${pageContext.request.contextPath}/schedule"><span class="quick-icon mint">▦</span><h3>Know what comes next</h3><p>View your assignments for the selected week.</p><span class="quick-link">Open planning ↗</span></a></c:otherwise></c:choose></div>
</main><footer>PeopleDesk · A better day at work</footer></body></html>