<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HR Management</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/app.css"></head><body>
<header class="workspace-header">
<a class="brand" href="${pageContext.request.contextPath}/dashboard"><span class="brand-symbol">p.</span><span>PeopleDesk<small>YOUR PEOPLE WORKSPACE</small></span></a>
<p class="nav-label">WORKSPACE</p>
<nav aria-label="Main navigation">
<a class="" href="${pageContext.request.contextPath}/dashboard"><span class="nav-icon">◈</span>Overview</a>
<c:if test="${me.role == 'ADMIN'}"><a class="active" href="${pageContext.request.contextPath}/employees"><span class="nav-icon">♧</span>Employees</a></c:if>
<a class="" href="${pageContext.request.contextPath}/absences"><span class="nav-icon">◷</span>Absences</a>
<a class="" href="${pageContext.request.contextPath}/messages"><span class="nav-icon">✉</span>Messages</a>
<a class="" href="${pageContext.request.contextPath}/schedule"><span class="nav-icon">▦</span>Planning</a>
<a class="" href="${pageContext.request.contextPath}/profile"><span class="nav-icon">◎</span>Profile</a>
</nav>
<section class="sidebar-tip"><span class="tip-dot"></span><strong>A little more organized.</strong><p>One space for your team,<br>your time and your next step.</p></section>
<div class="sidebar-account"><span class="avatar">${me.role == 'ADMIN' ? 'AD' : 'EM'}</span><div><strong><c:out value="${me.name}"/></strong><small>${me.role == 'ADMIN' ? 'Administrator' : 'Employee'}</small></div></div>
<form method="post" action="${pageContext.request.contextPath}/logout"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><button class="quiet">↗ Sign out</button></form>
</header>
<div class="topbar"><span>Workspace <span class="breadcrumb-divider">/</span> <strong>People management</strong></span><span class="workspace-pill"><span class="status-dot"></span>${me.role == 'ADMIN' ? 'Admin workspace' : 'Employee workspace'}</span></div><main><c:if test="${not empty notice}"><p class="notice" role="status"><c:out value="${notice}"/></p></c:if>
<p class="eyebrow">PEOPLE DIRECTORY</p><h1>Employees</h1><section class="card"><h2>${empty editing ? 'Add employee' : 'Edit employee'}</h2><form class="grid" method="post" action="${pageContext.request.contextPath}/employees"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="${empty editing ? 0 : editing.id}"><label>Full name<input name="name" value="<c:out value='${editing.name}'/>" required maxlength="100"></label><label>Email<input type="email" name="email" value="<c:out value='${editing.email}'/>" required maxlength="254"></label><label>Phone<input name="phone" value="<c:out value='${editing.phone}'/>" required maxlength="30"></label><label>Monthly salary<input type="number" name="salary" value="${editing.salary}" min="0" step="0.01" max="9999999999.99" required></label><label>Position<input name="position" value="<c:out value='${editing.position}'/>" required maxlength="100"></label><label>Role<select name="role"><option value="EMPLOYEE" ${editing.role == 'EMPLOYEE' ? 'selected' : ''}>Employee</option><option value="ADMIN" ${editing.role == 'ADMIN' ? 'selected' : ''}>Administrator</option></select></label><label>Password (12+ characters; leave blank to keep existing)<input type="password" name="password" minlength="12" maxlength="200" autocomplete="new-password" ${empty editing ? 'required' : ''}></label><div><button>Save employee</button><a href="${pageContext.request.contextPath}/employees">Cancel</a></div></form></section><section class="card table"><h2>Team directory</h2><table><thead><tr><th>Name</th><th>Email</th><th>Position</th><th>Salary</th><th>Role</th><th>Actions</th></tr></thead><tbody><c:forEach var="e" items="${employees}"><tr><td><c:out value="${e.name}"/></td><td><c:out value="${e.email}"/></td><td><c:out value="${e.position}"/></td><td><c:out value="${e.salary}"/></td><td><c:out value="${e.role}"/></td><td><a href="${pageContext.request.contextPath}/employees?edit=${e.id}">Edit</a><c:if test="${e.id != sessionScope.userId}"><form class="inline" method="post" action="${pageContext.request.contextPath}/employees"><input type="hidden" name="csrf" value="${sessionScope.csrf}"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="${e.id}"><button class="danger">Delete employee and related records</button></form></c:if></td></tr></c:forEach></tbody></table></section></main><footer>PeopleDesk · A better day at work</footer></body></html>