CREATE TABLE IF NOT EXISTS employee (
 id INTEGER AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE,
 phone VARCHAR(30) NOT NULL,
 salary DECIMAL(12,2) NOT NULL CHECK (salary >= 0),
 position VARCHAR(100) NOT NULL,
 role VARCHAR(10) NOT NULL CHECK (role IN ('ADMIN','EMPLOYEE')),
 password_hash VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS absence (
 id INTEGER AUTO_INCREMENT PRIMARY KEY,
 employee_id INTEGER NOT NULL,
 start_date DATE NOT NULL,
 days INTEGER NOT NULL CHECK (days BETWEEN 1 AND 365),
 reason VARCHAR(500) NOT NULL,
 FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS message (
 id INTEGER AUTO_INCREMENT PRIMARY KEY,
 sender_id INTEGER NOT NULL,
 recipient_id INTEGER NOT NULL,
 subject VARCHAR(200) NOT NULL,
 body VARCHAR(4000) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 FOREIGN KEY (sender_id) REFERENCES employee(id) ON DELETE CASCADE,
 FOREIGN KEY (recipient_id) REFERENCES employee(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS schedule_slot (
 id INTEGER AUTO_INCREMENT PRIMARY KEY,
 employee_id INTEGER NOT NULL,
 work_date DATE NOT NULL,
 task VARCHAR(100) NOT NULL,
 UNIQUE(employee_id,work_date),
 FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE
);
